import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts/fonts";
import Header from "./ui/components/Header";


export const metadata: Metadata = {
  title: "HomeCosts",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
